# Generated by Django 5.0.6 on 2024-05-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "station",
            },
        ),
        migrations.CreateModel(
            name="PassengerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=255)),
                (
                    "passenger_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "passengerInfo",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_station", models.CharField(max_length=50)),
                ("end_station", models.CharField(max_length=50)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.FloatField()),
                (
                    "station",
                    models.ManyToManyField(
                        related_name="routes", to="train_ticket_booking.station"
                    ),
                ),
            ],
            options={
                "db_table": "route",
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=20)),
                ("capacity", models.PositiveIntegerField()),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train_ticket_booking.route",
                    ),
                ),
            ],
            options={
                "db_table": "train",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("ticket_number", models.CharField(max_length=20, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("booked", "Booked"), ("cancelled", "Cancelled")],
                        default="booked",
                        max_length=20,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("Half Ticket", "Half Ticket"),
                            ("Full Ticket", "Full Ticket"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "passenger_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train_ticket_booking.passengerinfo",
                    ),
                ),
                (
                    "destination_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_reservations",
                        to="train_ticket_booking.station",
                    ),
                ),
                (
                    "source_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_reservation",
                        to="train_ticket_booking.station",
                    ),
                ),
                (
                    "train_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train_ticket_booking.train",
                    ),
                ),
            ],
            options={
                "db_table": "reservation",
            },
        ),
        migrations.CreateModel(
            name="RouteStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train_ticket_booking.route",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="train_ticket_booking.station",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("route", "station")},
            },
        ),
    ]
