# Generated by Django 5.0.6 on 2024-05-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_ticket_booking", "0003_alter_passengerinfo_passenger_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="ticket_type",
        ),
    ]
