# Generated by Django 5.0.6 on 2024-05-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_ticket_booking", "0004_remove_reservation_ticket_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="passenger_name",
            new_name="passengerinfo",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="train_name",
            new_name="train",
        ),
        migrations.RenameField(
            model_name="train",
            old_name="train_name",
            new_name="name",
        ),
    ]
