# Generated by Django 5.0.6 on 2024-05-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "train_ticket_booking",
            "0005_rename_passenger_name_reservation_passengerinfo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="train",
            old_name="name",
            new_name="train_name",
        ),
    ]
